repos:
- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: uv run mypy --follow-imports=silent --no-namespace-packages
      language: system
      types: [python]
      pass_filenames: true
      # exclude generated OAS sources from type checking
      exclude: ^(open_api/generated/|apib/|open_api/open_api_class_registry/)

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.15.6
  hooks:
    # Run the formatter.
    - id: ruff-format
    # Run the linter.
    - id: ruff-check
