repos: []
# disabled: started directly from ./git/pre-commit
#  - repo: local
#    hooks:
#      - id: build-and-stage
#        name: Build and stage generated files
#        language: system
#        entry: script/pre-commit-build
#        pass_filenames: false
#        always_run: false        # 👈 change this to false
#        files: ^wxc_sdk/.*\.py$         # 👈 only trigger if files under wxc_sdk/ are staged
#        stages: [pre-commit]