#!/usr/bin/env bash
# re-create all non API YML files
#
# Copyright (c) 2022 Johannes Krohn <jkrohn@cisco.com>
# License: MIT

#developer.webex.com/read_api_spec.py -f developer.webex.com/api_spec.yml
#developer.webex.com/read_api_spec.py -a developer.webex.com/.env -f developer.webex.com/auth_api_spec.yml
#developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Detailed Call History" -f developer.webex.com/cdr.yml
#developer.webex.com/read_api_spec.py -s "Full API Reference" -t "Report Templates" "Reports" -f developer.webex.com/reports.yml
#developer.webex.com/read_api_spec.py -s Messaging -t "Attachment Actions" Events Memberships Messages People "Room Tabs" "Rooms" "Team Memberships" Teams Webhooks -f developer.webex.com/messaging.yml
#developer.webex.com/read_api_spec.py -s Messaging -t Events -f developer.webex.com/events.yml
#developer.webex.com/read_api_spec.py -s Messaging -t Memberships -f developer.webex.com/memberships.yml
#developer.webex.com/read_api_spec.py -s Messaging -t Messages -f developer.webex.com/messages.yml
#developer.webex.com/read_api_spec.py -s Messaging -t People -f developer.webex.com/people.yml
#developer.webex.com/read_api_spec.py -s Messaging -t "Room Tabs" -f developer.webex.com/room_tabs.yml
#developer.webex.com/read_api_spec.py -s Messaging -t Rooms -f developer.webex.com/rooms.yml
#developer.webex.com/read_api_spec.py -s Messaging -t "Team Memberships" -f developer.webex.com/team_memberships.yml
#developer.webex.com/read_api_spec.py -s Messaging -t Teams -f developer.webex.com/teams.yml
#developer.webex.com/read_api_spec.py -s Messaging -t "Tracking Codes" -f developer.webex.com/tracking_codes.yml
#developer.webex.com/read_api_spec.py -s Messaging -t Webhooks -f developer.webex.com/webhooks.yml
#developer.webex.com/read_api_spec.py -s Calling -t "Webex Calling Voice Messaging" -f developer.webex.com/voice_messaging.yml
#developer.webex.com/read_api_spec.py -s Calling -t "Webex Calling Workspace Settings" -f developer.webex.com/wxc_ws_settings.yml

# developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Organization Settings with Devices Features" -f developer.webex.com/wxc_cust_devices.yml
# developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Organization Settings with Customer Managed Devices Features" -f developer.webex.com/wxc_cust_devices.yml
# developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Organization Settings With Non Geographical Number" -f org_w_non_geo_number.yml
# developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Person Settings With Shared Line" -f person_w_shared_line.yml
# developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Person Settings with Calling Behavior" -f person_w_calling_behavior.yml
# developer.webex.com/read_api_spec.py -s Meetings -f developer.webex.com/meetings.yml


# toggled features 3.2.23
developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Organization Settings With Location Receptionist Directories" -f developer.webex.com/receptionist_client.yml
developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Organization Settings with Customer Managed Devices Features" -f developer.webex.com/cust_managed_devices.yml
developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Person Settings With Shared Line" -f developer.webex.com/person_shared_lines.yml
developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Person Settings with Call Bridge Feature" -f developer.webex.com/person_call_bridge.yml
developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Person Settings with Customer Managed Device Features" -f developer.webex.com/person_customer_managed_devices.yml


for i in developer.webex.com/*.yml; do developer.webex.com/classes.py "$i" -o "${i/.yml/_auto.py}"; done
