#!/usr/bin/env bash
# re-create all non API YML files
#
# Copyright (c) 2022 Johannes Krohn <jkrohn@cisco.com>
# License: MIT

developer.webex.com/read_api_spec.py -f developer.webex.com/api_spec.yml
developer.webex.com/read_api_spec.py -a developer.webex.com/.env -f developer.webex.com/auth_api_spec.yml
developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Detailed Call History" -f developer.webex.com/cdr.yml
developer.webex.com/read_api_spec.py -s "Full API Reference" -t "Report Templates" "Reports" -f developer.webex.com/reports.yml
developer.webex.com/read_api_spec.py -s Messaging -t Events -f developer.webex.com/events.yml
developer.webex.com/read_api_spec.py -s Messaging -t Memberships -f developer.webex.com/memberships.yml
developer.webex.com/read_api_spec.py -s Messaging -t Messages -f developer.webex.com/messages.yml
developer.webex.com/read_api_spec.py -s Messaging -t People -f developer.webex.com/people.yml
developer.webex.com/read_api_spec.py -s Messaging -t "Room Tabs" -f developer.webex.com/room_tabs.yml
developer.webex.com/read_api_spec.py -s Messaging -t Rooms -f developer.webex.com/rooms.yml
developer.webex.com/read_api_spec.py -s Messaging -t "Team Memberships" -f developer.webex.com/team_memberships.yml
developer.webex.com/read_api_spec.py -s Messaging -t Teams -f developer.webex.com/teams.yml
developer.webex.com/read_api_spec.py -s Messaging -t "Attachment Actions" Events Memberships Messages, People, "Room Tabs" "Rooms" "Team Memberships" Teams Webhooks -f developer.webex.com/messaging.yml

for i in developer.webex.com/*.yml; do developer.webex.com/classes.py "$i" -o "${i/.yml/_auto.py}"; done
