#!/usr/bin/env bash
# re-create all non API YML files
#
# Copyright (c) 2022 Johannes Krohn <jkrohn@cisco.com>
# License: MIT


developer.webex.com/read_api_spec.py -f developer.webex.com/generated/api_spec.yml
developer.webex.com/read_api_spec.py -a developer.webex.com/.env -f developer.webex.com/generated/auth_api_spec.yml
developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Detailed Call History" -f developer.webex.com/generated/cdr.yml
developer.webex.com/read_api_spec.py -s "Full API Reference" -t "Report Templates" "Reports" -f developer.webex.com/generated/reports.yml
developer.webex.com/read_api_spec.py -s Calling -t "Webex Calling Voice Messaging" -f developer.webex.com/generated/voice_messaging.yml
developer.webex.com/read_api_spec.py -s Calling -t "Webex Calling Workspace Settings" -f developer.webex.com/generated/wxc_ws_settings.yml
developer.webex.com/read_api_spec.py -s "Full API Reference"  -t "Workspace Locations" -f developer.webex.com/generated/ws_locations.yml
developer.webex.com/read_api_spec.py -s "Full API Reference"  -t "Workspaces" -f developer.webex.com/generated/workspaces.yml

# non calling related
developer.webex.com/read_api_spec.py -s Messaging -t "Attachment Actions" Events Memberships Messages People "Room Tabs" "Rooms" "Team Memberships" Teams Webhooks -f developer.webex.com/generated/messaging.yml
developer.webex.com/read_api_spec.py -s Messaging -t Events -f developer.webex.com/generated/events.yml
developer.webex.com/read_api_spec.py -s Messaging -t Memberships -f developer.webex.com/generated/memberships.yml
developer.webex.com/read_api_spec.py -s Messaging -t Messages -f developer.webex.com/generated/messages.yml
developer.webex.com/read_api_spec.py -s Messaging -t People -f developer.webex.com/generated/people.yml
developer.webex.com/read_api_spec.py -s Messaging -t "Room Tabs" -f developer.webex.com/generated/room_tabs.yml
developer.webex.com/read_api_spec.py -s Messaging -t Rooms -f developer.webex.com/generated/rooms.yml
developer.webex.com/read_api_spec.py -s Messaging -t "Team Memberships" -f developer.webex.com/generated/team_memberships.yml
developer.webex.com/read_api_spec.py -s Messaging -t Teams -f developer.webex.com/generated/teams.yml
developer.webex.com/read_api_spec.py -s Messaging -t "Tracking Codes" -f developer.webex.com/generated/tracking_codes.yml
developer.webex.com/read_api_spec.py -s Messaging -t Webhooks -f developer.webex.com/generated/webhooks.yml

# this stuff is not under a toggle anymore
#developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Organization Settings with Devices Features" -f developer.webex.com/generated/wxc_cust_dev_features.yml
#developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Organization Settings with Customer Managed Devices Features" -f developer.webex.com/generated/wxc_cust_devices.yml
#developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Organization Settings With Non Geographical Number" -f org_w_non_geo_number.yml
#developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Person Settings With Shared Line" -f person_w_shared_line.yml
#developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Person Settings with Calling Behavior" -f person_w_calling_behavior.yml
#developer.webex.com/read_api_spec.py -s Meetings -f developer.webex.com/generated/meetings.yml


# toggled features 3.2.23?
#developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Organization Settings With Location Receptionist Directories" -f developer.webex.com/generated/generated/receptionist_client.yml
#developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Organization Settings with Customer Managed Devices Features" -f developer.webex.com/generated/cust_managed_devices.yml
#developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Person Settings With Shared Line" -f developer.webex.com/generated/person_shared_lines.yml
#developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Person Settings with Call Bridge Feature" -f developer.webex.com/generated/person_call_bridge.yml
#developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Webex Calling Person Settings with Customer Managed Device Features" -f developer.webex.com/generated/person_customer_managed_devices.yml

developer.webex.com/read_api_spec.py --no_ignore -s "Full API Reference" -f developer.webex.com/generated/full_spec.yml
developer.webex.com/endpoint_summary.py developer.webex.com/generated/full_spec.yml -o developer.webex.com/generated/full_spec.csv

#
developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Devices -t "Devices with WXC Devices Displayed" -f developer.webex.com/generated/devices_w_wxc.yml
developer.webex.com/read_api_spec.py -a developer.webex.com/.env -s Calling -t "Workspaces with WXC Included" -f developer.webex.com/generated/workspaces_w_wxc.yml

# announcement repository
developer.webex.com/read_api_spec.py --auth developer.webex.com/.env -s "Webex Calling" -t "Webex Calling Organization Settings with Announcements Repository Feature" -f developer.webex.com/generated/announcement_rep.yml
developer.webex.com/read_api_spec.py --auth developer.webex.com/.env -s "Full API Reference" -t "Beta Features: Announcement Repository with Announcements Repository Feature" -f developer.webex.com/generated/announcement_repo.yml

# Device Call Settings
developer.webex.com/read_api_spec.py --auth developer.webex.com/.env -s "Webex Calling" -t "Device Call Settings" -f developer.webex.com/generated/device_call_settings.yml

# User Call Settings
developer.webex.com/read_api_spec.py --auth developer.webex.com/.env -s "Full API Reference" -t "User Call Settings" -f developer.webex.com/generated/user_call_settings.yml

for i in developer.webex.com/generated/*.yml; do developer.webex.com/classes.py "$i" -o "${i/.yml/_auto.py}"; done
