#!/usr/bin/env bash
# Build the project's product(s).
#
# Copyright (c) 2022 Johannes Krohn <jkrohn@cisco.com>
# License: MIT


set -e
cd "$(dirname "$0")/.."


# Default build
all=true


# Process Script Arguments
for i in ${@}; do
    case ${i} in
        package)
        all=
        package=true
        ;;

        docs)
        all=
        docs=true
        ;;

        types)
        all=
        types=true
        ;;

        *)
        echo "Unknown argument: $i"
        exit 1
        ;;
    esac
done


echo "==> Cleaning previous build artifacts"
script/clean


if [ ${all} ] || [ ${types} ]; then
    echo "==> Creating types.py"
    script/all_types.py
fi


if [ ${all} ] || [ ${docs} ]; then
    echo "==> Building the Docs"
    make -C docs clean
    sphinx-apidoc -o docs/apidoc -f -e -M wxc_sdk 'wxc_sdk/types.py'
    make -C docs html
fi


# Project build steps
if [ ${all} ] || [ ${package} ]; then
    echo "==> Building the Source Distribution package"
    poetry build
fi

