#!/usr/bin/env bash
# Open the project's console.
#
# Copyright (c) 2022 Johannes Krohn <jkrohn@cisco.com>
# License: MIT


set -e
cd "$(dirname "$0")/.."


# Launch the project's console
ipython -i script/ipython_console.py
