#!/usr/bin/env bash
# Setup or reset the project to its initial state.
#
# Copyright (c) 2022 Johannes Krohn <jkrohn@cisco.com>
# License: MIT


set -e
cd "$(dirname "$0")/.."


echo "==> Setting up / resetting project for initial use"

script/clean --deep
script/installdeps
